# data
seed: 0
data_dim: 10
latent_dim: 4
relevant_latents: 4
latent_case: "scm_dense"
poly_degree: 2
train_size: 500
test_size: 500

# training
epochs: 30
batch_size: 64
use_scm: True

# scm specific
# use_z:
use_fixed_A: True

# explanation
n_samples: 25

